function dyn = furataDynamics(theta,alpha,theta_dot,alpha_dot,tau)
%FURATADYNAMICS
%    DYN = FURATADYNAMICS(THETA,ALPHA,THETA_DOT,ALPHA_DOT,TAU)

%    This function was generated by the Symbolic Math Toolbox version 8.0.
%    04-Dec-2018 14:24:15

t2 = cos(alpha);
t3 = sin(alpha);
t4 = t2.^2;
t5 = t4.*2.189239607897576e31;
t6 = t5+2.395116244720808e32;
t7 = 1.0./t6;
t8 = theta_dot.^2;
t9 = alpha_dot.^2;
dyn = [theta_dot;alpha_dot;t7.*(tau.*-1.132527773586268e37+theta_dot.*1.698791660379401e34+alpha_dot.*t2.*5.596794229932136e33+t2.*t3.*1.699844911208837e35+t3.*t9.*1.490180044484811e33-t3.*t4.*t8.*1.117635033363608e33+alpha_dot.*t2.*t3.*theta_dot.*2.26156736162989e33).*(-8.0./1.25e2);t7.*(alpha_dot.*-1.405552976224484e34-t3.*4.268911766117573e35+alpha_dot.*t4.*4.246979150948503e33+t3.*t4.*1.289882314976117e35-t2.*tau.*1.119358845986427e37+t2.*theta_dot.*1.679038268979641e34+t2.*t3.*t8.*2.806776849282196e33+t2.*t3.*t9.*1.472852369548941e33+alpha_dot.*t3.*t4.*theta_dot.*2.235270066727216e33-t2.*t3.*t4.*t8.*8.480877606112085e32).*(8.0./1.25e2)];
